import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster"
const inter = Inter({ subsets: ['latin'] })
import { TrpcProvider } from "@/utils/trpc-provider";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/f0c2f16b90.js" crossOrigin="anonymous"></script>

      </head>
      <body>
        <TrpcProvider>{children}</TrpcProvider>
        <Toaster />
      </body>

    </html>
  );
}

